// atomic/pages/general.tsx
'use client'

import { usePathname } from 'next/navigation'
import type { JSX } from 'react'
import { useEffect, useMemo, useState } from 'react'

import type { TileInterface } from 'nucleify'
import {
  articleRequests,
  contactRequests,
  isMobile,
  moneyRequests,
  NucArticleDashboard,
  NucContactDashboard,
  NucEntityChartCard,
  NucMoneyDashboard,
  NucTiles,
  t,
} from 'nucleify'

export function NucEntitiesPage(): JSX.Element {
  const pathname = usePathname()
  const lang = pathname.split('/').filter(Boolean).at(0) || 'en'
  const {
    results: articles,
    createdLastWeek: articlesCreatedLastWeek,
    loading: articlesLoading,
    getAllArticles,
    getCountArticlesByCreatedLastWeek,
  } = articleRequests(undefined, 'next')
  const {
    results: contacts,
    createdLastWeek: contactsCreatedLastWeek,
    loading: contactsLoading,
    getAllContacts,
    getCountContactsByCreatedLastWeek,
  } = contactRequests(undefined, 'next')
  const {
    results: money,
    createdLastWeek: moneyCreatedLastWeek,
    loading: moneyLoading,
    getAllMoney,
    getCountMoneyByCreatedLastWeek,
  } = moneyRequests(undefined, 'next')
  const [allLoaded, setAllLoaded] = useState<boolean>(false)

  useEffect(() => {
    void getAllArticles(true)
    void getAllContacts(true)
    void getAllMoney(true)
    void getCountArticlesByCreatedLastWeek()
    void getCountContactsByCreatedLastWeek()
    void getCountMoneyByCreatedLastWeek()
  }, [])

  useEffect(() => {
    if (!articlesLoading && !contactsLoading && !moneyLoading) {
      const timeout = setTimeout(() => {
        setAllLoaded(true)
      }, 200)
      return () => clearTimeout(timeout)
    }
    setAllLoaded(false)
    return
  }, [articlesLoading, contactsLoading, moneyLoading])

  const entities = useMemo<TileInterface[]>(
    () => [
      {
        href: `/${lang}/entities/articles`,
        header: t('admin-tile-articles'),
        count: articles?.length || 0,
        icon: 'prime:comment',
        countSecondary: articlesCreatedLastWeek || 0,
        textSecondary: t('admin-tile-this-week'),
      },
      {
        href: `/${lang}/entities/contacts`,
        header: t('admin-tile-contacts'),
        count: contacts?.length || 0,
        icon: 'prime:user',
        countSecondary: contactsCreatedLastWeek || 0,
        textSecondary: t('admin-tile-this-week'),
      },
      {
        href: `/${lang}/entities/money`,
        header: t('admin-tile-money'),
        count: money?.length || 0,
        icon: 'prime:dollar',
        countSecondary: moneyCreatedLastWeek || 0,
        textSecondary: t('admin-tile-this-week'),
      },
    ],
    [
      articles,
      contacts,
      money,
      articlesCreatedLastWeek,
      contactsCreatedLastWeek,
      moneyCreatedLastWeek,
      lang,
    ]
  )

  return (
    <div className="panel-container">
      <NucTiles entities={entities} />
      <NucEntityChartCard
        entity="Entities"
        chartClass="annual-chart-card"
        chartMethodType="annual"
        type="bar"
        direction={isMobile() ? 'horizontal' : 'vertical'}
        data={{
          article: articles,
          contact: contacts,
          money: money,
        }}
        loading={!allLoaded}
      />
      <NucArticleDashboard
        data={articles ?? []}
        getData={getAllArticles}
        loading={!allLoaded}
      />
      <NucContactDashboard
        data={contacts ?? []}
        getData={getAllContacts}
        loading={!allLoaded}
      />
      <NucMoneyDashboard
        data={money ?? []}
        getData={getAllMoney}
        loading={!allLoaded}
      />
    </div>
  )
}

// atomic/pages/General/index.vue
<!--suppress HtmlUnknownAnchorTarget -->
<template>
  <div class="panel-container">
    <nuc-tiles :entities="entities" />

    <nuc-entity-chart-card
      entity="Entities"
      class="annual-chart-card"
      chart-method-type="annual"
      type="bar"
      :direction="isMobile() ? 'horizontal' : 'vertical'"
      :data="{ 
        article: articles, 
        contact: contacts, 
        money: money 
      }"
      :loading="!allLoaded"
    />

    <nuc-article-dashboard
      :data="articles"
      :get-data="getAllArticles"
      :loading="!allLoaded"
    />
    <nuc-contact-dashboard
      :data="contacts"
      :get-data="getAllContacts"
      :loading="!allLoaded"
    />
    <nuc-money-dashboard
      :data="money"
      :get-data="getAllMoney"
      :loading="!allLoaded"
    />
  </div>
</template>

<script setup lang="ts">
import type { TileInterface } from 'atomic'
import { articleRequests, contactRequests, moneyRequests } from 'atomic'

const {
  results: articles,
  createdLastWeek: articlesCreatedLastWeek,
  loading: articlesLoading,
  getAllArticles,
  getCountArticlesByCreatedLastWeek,
} = articleRequests()
const {
  results: contacts,
  createdLastWeek: contactsCreatedLastWeek,
  loading: contactsLoading,
  getAllContacts,
  getCountContactsByCreatedLastWeek,
} = contactRequests()
const {
  results: money,
  createdLastWeek: moneyCreatedLastWeek,
  loading: moneyLoading,
  getAllMoney,
  getCountMoneyByCreatedLastWeek,
} = moneyRequests()

onMounted(() => {
  getAllArticles(true)
  getAllContacts(true)
  getAllMoney(true)
  getCountArticlesByCreatedLastWeek()
  getCountContactsByCreatedLastWeek()
  getCountMoneyByCreatedLastWeek()
})

const allLoaded: Ref<boolean> = ref(false)

watch(
  [articlesLoading, contactsLoading, moneyLoading],
  ([articlesLoading, contactsLoading, moneyLoading]: [
    boolean,
    boolean,
    boolean,
  ]) => {
    if (!articlesLoading && !contactsLoading && !moneyLoading) {
      setTimeout(() => {
        allLoaded.value = true
      }, 200)
    }
  }
)

const entities = computed<TileInterface[]>(() => [
  {
    href: '/entities/articles',
    header: 'Articles',
    count: articles.value?.length || 0,
    icon: 'prime:comment',
    countSecondary: articlesCreatedLastWeek.value,
    textSecondary: 'this week',
    adType: 'article',
  },
  {
    href: '/entities/contacts',
    header: 'Contacts',
    count: contacts.value?.length || 0,
    icon: 'prime:user',
    countSecondary: contactsCreatedLastWeek.value,
    textSecondary: 'this week',
    adType: 'contact',
  },
  {
    href: '/entities/money',
    header: 'Money',
    count: money.value?.length || 0,
    icon: 'prime:dollar',
    countSecondary: moneyCreatedLastWeek.value,
    textSecondary: 'this week',
    adType: 'money',
  },
])
</script>
