// atomic/pages/article.tsx
'use client'

import type { JSX } from 'react'
import { useEffect } from 'react'

import {
  articleRequests,
  isMobile,
  NucArticleDashboard,
  NucEntityChartCard,
  useNucDialog,
} from 'nucleify'

export function NucArticlePage(): JSX.Element {
  const { closeDialog } = useNucDialog()
  const { loading, results, getAllArticles } = articleRequests(
    closeDialog,
    'next'
  )

  useEffect(() => {
    void getAllArticles(true)
  }, [])

  return (
    <div className="panel-container">
      <NucEntityChartCard
        entity="Article"
        chartClass="annual-chart-card"
        chartMethodType="annual"
        type="bar"
        direction={isMobile() ? 'horizontal' : 'vertical'}
        data={{ article: results }}
        loading={loading}
      />
      <NucArticleDashboard
        data={results ?? []}
        getData={getAllArticles}
        loading={loading}
      />
    </div>
  )
}

// atomic/pages/Article/index.vue
<template>
  <div class="panel-container">
    <nuc-entity-chart-card
      entity="Article"
      class="annual-chart-card"
      chart-method-type="annual"
      type="bar"
      :direction="isMobile() ? 'horizontal' : 'vertical'"
      :data="{ article: results }"
      :loading="loading"
    />
    <nuc-article-dashboard
      :data="results"
      :get-data="getAllArticles"
      :loading="loading"
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

import { articleRequests, useNucDialog } from 'nucleify'

const { closeDialog } = useNucDialog()

const { results, loading, getAllArticles } = articleRequests(closeDialog)

onMounted(() => {
  getAllArticles(true)
})
</script>
