// pages/contact.tsx
'use client'

import type { JSX } from 'react'
import { useEffect } from 'react'

import {
  contactRequests,
  isMobile,
  NucContactDashboard,
  NucEntityChartCard,
  useNucDialog,
} from 'nucleify'

export function NucContactPage(): JSX.Element {
  const { closeDialog } = useNucDialog()
  const { loading, results, getAllContacts } = contactRequests(
    closeDialog,
    'next'
  )

  useEffect(() => {
    void getAllContacts(true)
  }, [])

  return (
    <div className="panel-container">
      <NucEntityChartCard
        entity="Contact"
        chartClass="annual-chart-card"
        chartMethodType="annual"
        type="bar"
        direction={isMobile() ? 'horizontal' : 'vertical'}
        data={{ contact: results }}
        loading={loading}
      />
      <NucContactDashboard
        data={results ?? []}
        getData={getAllContacts}
        loading={loading}
      />
    </div>
  )
}

// atomic/pages/Contact/index.vue
<template>
  <div class="panel-container">
    <nuc-entity-chart-card
      entity="Contact"
      class="annual-chart-card"
      chart-method-type="annual"
      type="bar"
      :direction="isMobile() ? 'horizontal' : 'vertical'"
      :data="{ contact: results }"
      :loading="loading"
    />
    <nuc-contact-dashboard
      :data="results"
      :get-data="getAllContacts"
      :loading="loading"
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

import { contactRequests, useNucDialog } from 'atomic'

const { closeDialog } = useNucDialog()

const { loading, results, getAllContacts } = contactRequests(closeDialog)

onMounted(() => {
  getAllContacts(true)
})
</script>
