// atomic/pages/Money/index.vue
<template>
  <div class="panel-container">
    <nuc-entity-chart-card
      entity="Money"
      class="annual-chart-card"
      chart-method-type="annual"
      type="bar"
      :direction="isMobile() ? 'horizontal' : 'vertical'"
      :data="{ money: results }"
      :loading="loading"
    />
    <nuc-money-dashboard
      :data="results"
      :get-data="getAllMoney"
      :loading="loading"
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

import { moneyRequests, useNucDialog } from 'atomic'

const { closeDialog } = useNucDialog()

const { loading, results, getAllMoney } = moneyRequests(closeDialog)

onMounted(() => {
  getAllMoney(true)
})
</script>

// pages/money.tsx
'use client'

import type { JSX } from 'react'
import { useEffect } from 'react'

import {
  isMobile,
  moneyRequests,
  NucEntityChartCard,
  NucMoneyDashboard,
  useNucDialog,
} from 'nucleify'

export function NucMoneyPage(): JSX.Element {
  const { closeDialog } = useNucDialog()
  const { loading, results, getAllMoney } = moneyRequests(closeDialog, 'next')

  useEffect(() => {
    void getAllMoney(true)
  }, [])

  return (
    <div className="panel-container">
      <NucEntityChartCard
        entity="Money"
        chartClass="annual-chart-card"
        chartMethodType="annual"
        type="bar"
        direction={isMobile() ? 'horizontal' : 'vertical'}
        data={{ money: results }}
        loading={loading}
      />
      <NucMoneyDashboard
        data={results ?? []}
        getData={getAllMoney}
        loading={loading}
      />
    </div>
  )
}
